version: 0.2
env:
  variables:
    DB_PORT: 5234
  exported-variables:
    DB_NAME
    DB_USERNAME
    DB_PASSWORD
    DB_HOST
proxy:
  upload-artifacts: no
  logs: no

batch:
  fast-fail: false
        
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip3 install -r requirements/codebuild/db.txt
  build:
    commands:
      - cd db
      - alembic upgrade head
      - echo "FINISH"