variable "region" {}
variable "account_id" {}
variable "lambdas_names" {}
variable "api_gateway_references" {}
variable "aws_iam_policy_network_arn" {}
variable "aws_iam_policy_logs_arn" {}
variable "environment" {}
variable "glue_trigger_arn" {}
variable "bucket_files" {}
