name: CD process to deploy to backend service

on:
  # Trigger the workflow on push event in the master branch
  push:
    branches:
      - master

jobs:
  ci-test:
    name: Unit tests and CodeCoverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.X'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'coverage[toml]' pytest pytest-cov
          pip install -r requirements/prod.txt
      - name: Run Unit Tests
        run: |
           python -m pytest src/tests
      - name: Generate coverage
        run: |
          python -m pytest --cache-clear --cov-config=.coveragerc --cov=src/ src/tests/*
      - name: Check threshold of coverage
        run: |
          coverage report -m --fail-under=100