name: SonarCloud analysis

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, edited, reopened, synchronize]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.X'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'coverage[toml]' pytest pytest-cov
          pip install -r requirements/prod.txt
      - name: Running pytest
        run: |
          pytest --cov=src --cov-report xml:coverage.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: src/
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.test.exclusions=tests/**
            -Dsonar.sources=service/,handlers/
            -Dsonar.python.version=3
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}